Assistant checkpoint: Fix calendar error, add analytics and customer history
Assistant generated file changes:
- users/models.py: Fix get_participant_count method to use correct related name
- users/templates/users/dive_calendar.html: Add links to dive details in calendar list
- users/views.py: Add customer activity history view
- users/templates/users/customer_list.html: Add activity history button to customer list
- users/templates/users/customer_activity_history.html: Create customer activity history template
- users/templates/users/dashboard_analytics.html: Create dashboard analytics template
- users/templates/users/diving_center_dashboard.html: Add analytics button to dashboard
- users/urls.py: Add new URLs for analytics and customer history

---

User prompt:

I'm having this error when I access the calendar view:
AttributeError at /users/calendar-view/
'DiveSchedule' object has no attribute 'customerdiveactivity_set'

I also need to access the scheduled dives using the rute: "/users/calendar/" It shows the list of upcoming dives but I can not access to them.

For every user I need an history of all the activities they have done. In the user list create a new button to access a new page where I can see a log of everithing.

I also need in the dashboard an option to see some statistics like a chart to see the age range, the amount of people from each country, the average of activities every person does, a linear chart to see the amount of people coming to do activities every day of the year and some things like this to analize the behavour of my customers.

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: 327e2aaf-01e1-476f-aed0-0595be6b227b